[build]
  # Netlify will run 'npm run build' to build the React app
  command = "npm run build"
  # The 'build' folder where the final built app is stored
  publish = "build"

[[redirects]]
  # Redirect all routes to index.html for React Router (important for client-side routing)
  from = "/*"
  to = "/index.html"
  status = 200