# basic docker-compose file, should be updated when project will be done
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=d-k1n((!vuupr&2m^8-m6wjr4a&g77xp=@gvr7x5(z4@95b%z6
      - DEBUG=TRUE
      - MONGO_URI=mongodb+srv://sinchuk_taras:sinchuk_password@dbpk-merch.gffoef9.mongodb.net/store?retryWrites=true&w=majority&appName=DBPK-Merch
      - DJANGO_SETTINGS_MODULE=store.settings


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  media_volume: